// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLrdcRNpGvwhcF2ANMw-kLUON0FFAKq7E',
    appId: '1:6543386869:web:7f8f7ca70bd1c117d77dbc',
    messagingSenderId: '6543386869',
    projectId: 'smart-home-test-c9205',
    authDomain: 'smart-home-test-c9205.firebaseapp.com',
    storageBucket: 'smart-home-test-c9205.firebasestorage.app',
    measurementId: 'G-7RE8X4KTLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtblEiFDAgcGEx_Zi1IEFRi6yEfAOP_qE',
    appId: '1:6543386869:android:7f1ad1d79d98ea5fd77dbc',
    messagingSenderId: '6543386869',
    projectId: 'smart-home-test-c9205',
    storageBucket: 'smart-home-test-c9205.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQijAaZs-C7a9Ny3mf2Pm1aGQDYsOXdMs',
    appId: '1:6543386869:ios:0c4bef36ce12b46fd77dbc',
    messagingSenderId: '6543386869',
    projectId: 'smart-home-test-c9205',
    storageBucket: 'smart-home-test-c9205.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQijAaZs-C7a9Ny3mf2Pm1aGQDYsOXdMs',
    appId: '1:6543386869:ios:0c4bef36ce12b46fd77dbc',
    messagingSenderId: '6543386869',
    projectId: 'smart-home-test-c9205',
    storageBucket: 'smart-home-test-c9205.firebasestorage.app',
    iosBundleId: 'com.example.smartHomeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLrdcRNpGvwhcF2ANMw-kLUON0FFAKq7E',
    appId: '1:6543386869:web:e9efe9d31de30be6d77dbc',
    messagingSenderId: '6543386869',
    projectId: 'smart-home-test-c9205',
    authDomain: 'smart-home-test-c9205.firebaseapp.com',
    storageBucket: 'smart-home-test-c9205.firebasestorage.app',
    measurementId: 'G-RDE8XKD8TS',
  );
}
